"""address in events

Revision ID: 1f4025a00a3d
Revises: d3219370be01
Create Date: 2023-07-19 16:32:21.456064

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "1f4025a00a3d"
down_revision = "d3219370be01"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
