"""tour_module

Revision ID: bf214d866fe9
Revises: 51714ebec258
Create Date: 2023-08-01 17:56:04.999583

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf214d866fe9'
down_revision = '51714ebec258'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tour',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('date_start', sa.TIMESTAMP(), nullable=True),
    sa.Column('date_end', sa.TIMESTAMP(), nullable=True),
    sa.Column('reg_deadline', sa.TIMESTAMP(), nullable=True),
    sa.Column('max_users', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tour_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tour_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.ForeignKeyConstraint(['tour_id'], ['tour.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tour_event')
    op.drop_table('tour')
    # ### end Alembic commands ###
